[font]
size = 14
normal = { family = "Inconsolata  Nerd  Font", style = "Regular" }

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[colors.normal]
black = "#121212"
red = "#C34043"
green = "#5F875F"
yellow = "#C0A36E"
blue = "#7E9CD8"
magenta = "#957FB8"
cyan = "#5F8787"
white = "#C5C9C5"

[colors.bright]
black = "#727169"
red = "#E82424"
green = "#98BB6C"
yellow = "#E6C384"
blue = "#7FB4CA"
magenta = "#938AA9"
cyan = "#7AA89F"
white = "#DCD7BA"

[colors.selection]
background = "#C0A36E"
foreground = "#090618"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[window]
decorations = "none"
startup_mode = "Maximized"

[mouse]
hide_when_typing = true

[terminal]

[terminal.shell]
program = "/bin/zsh"
args = ["-c", "tmux -2 new -s0 -A"]
