---
- name: Setup Development Environment
  hosts: localhost
  tasks:
    - name: Install environment requirements
      become: true
      community.general.pacman:
        name:
          - alacritty
          - bat
          - bazel
          - cmake
          - docker
          - diff-so-fancy
          - fd
          - fzf
          - git
          - go
          - jq
          - lf
          - man-db
          - moreutils
          - neovim
          - npm
          - pipewire
          - pipewire-pulse
          - python-pip
          - python-pynvim
          - python-pyqt5
          - python-virtualenv
          - ripgrep
          - ruby
          - rust
          - seahorse
          - terraform
          - texlive
          - tig
          - tmux
          - traceroute
          - wget
          - xclip
          - xterm
          - zsh
        update_cache: true
        state: present

    - name: Install Yay
      shell: "[ -d ~/Downloads/yay ] || git clone https://aur.archlinux.org/yay.git ~/Downloads/yay && cd ~/Downloads/yay && makepkg -si --noconfirm"

    - name: Install AUR packages
      shell:
        cmd: |
          yay -S --noconfirm \
            antigen \
            noto-fonts \
            noto-fonts-cjk \
          && sudo rm /usr/share/fonts/noto/NotoNastaliq*

    - name: Copy dotfiles to home directory
      shell: bash -c "ls --hide=setup.yml | xargs -i bash -c 'rsync -a {}/. ~/.{} 2>/dev/null || rsync -a {} ~/.{}'"

    - name: Set Zsh as default shell
      become: true
      shell: chsh -s /bin/zsh

    - name: Install Vim plugins
      command: nvim +PackerSync +qall

    - name: Airline Zsh
      shell: nvim +"PromptlineSnapshot! /tmp/promptline.sh airline" +qall && cat /tmp/promptline.sh >> ~/.zshrc

    - name: Airline Tmux
      shell: nvim +"TmuxlineSnapshot! /tmp/tmuxline.conf" +qall && cat /tmp/tmuxline.conf >> ~/.tmux.conf
